### PR TITLE
Implemented FilterId for all Read methods

### LINKED ISSUE #111: SAP2000_Toolkit: Add filter by object id
#### Description:

- Create a new method FilterIds( requestIds, sapIds ) which takes the intersection of the two lists (if requestIds is not null).
- Implement the method in all Read methods as applicable

See [ETABS #306](https://github.com/BHoM/ETABS_Toolkit/pull/306)

### LINKED ISSUE #127: SAP2000_Toolkit: Selection Filter Request
#### Description:
Implement SelectionFilterRequest using SAP `GetSelected()`

### PR DESCRIPTION
**Pull request by maryannewachter**
### Issues addressed by this PR

Closes #111 
Closes #127 

All SAP elements that can be read can now be filtered if the SAP object ID is known.
Active selection in SAP can be pulled into the BHoM.

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/SAP2000_Toolkit/%23111-FilterRequestByObjectId?csf=1&web=1&e=8k6Jc2

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
This PR will need a label before merging just as a reminder 😄

**Review by JosefTaylor — APPROVED** [review]
Works, but is slow for large models- pulling all bars (2000 of them) takes 22 seconds, pulling just one takes 20 seconds. That two seconds is nice but would be nice to cut more!

**Comment by JosefTaylor** [comment]
@BHoMBot check installer

**Pull request merged**
