### PR TITLE
Implemented Bar Utilisation Read Functionality

### LINKED ISSUE #183: Add Additional BarResults Pull Functionality
#### Description:
Add ability to get more BarResults beyond BarForces.

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #183 

Added ability to pull utilisation results from SAP. This includes the addition of a new AISCSteelUtilisationClass and corresponding request and enum as per discussion with @JosefTaylor and @IsakNaslundBh . Long term, these additions should be migrated to BHoM as they are not SAP-specific.

### Test files
[PullSAPUtilisation.zip](https://github.com/BHoM/SAP2000_Toolkit/files/5897225/PullSAPUtilisation.zip)

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check installer

**Review by JosefTaylor — DISMISSED** [review]
This looks good to me, and works. I'd suggest changing the enum to the whole list of SAP design codes (you won't have to change much else, even if you choose to support different editions of AISC, as your switch/case will just fall through the rest of the enum)

**Comment by enarhi** [comment]
@BHoMBot check installer and check compliance

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Review by JosefTaylor — DISMISSED** [review]
LGTM!

**Review by JosefTaylor — APPROVED** [review]
great!

**Comment by JosefTaylor** [comment]
@BHoMBot check installer
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check installer

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
Closing this PR, replaced by https://github.com/BHoM/SAP2000_Toolkit/pull/197

**Pull request closed without merging**
