### PR TITLE
Update Assembly Version

### LINKED ISSUE #223: Update AssemblyFileVersion
The `AssemblyFileVersion` attribute should now be updated to read `4.2.0.0` for all `AssemblyInfo.cs` files within this repository for the 4.2 milestone.

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #223

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed from a CI/CD perspective. Will let discipline merge when happy.

**Comment by JosefTaylor** [comment]
@BHoMBot check core

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Review by JosefTaylor — APPROVED** [review]
It didn't break!

**Comment by JosefTaylor** [comment]
@BHoMBot check versioning

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2241543630

**Pull request merged**
