### PR TITLE
BarTemperatureLoad Implementation

### LINKED ISSUE #141: SAP2000_Toolkit: Add BarTemperatureLoad
#### Description:
Add functionality for handling BarTemperatureLoad

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #141 

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/SAP2000_Toolkit/141%20-%20Issue%20-%20BarTemperatureLoad?csf=1&web=1&e=IWVUdc

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check documentation compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Review by maryannewachter — APPROVED** [review]
Read method was missing, now added and tested. Works as expected.

**Pull request merged**
