### PR TITLE
Update copyright headers to 2023 for new files

### LINKED ISSUE #279: Fix Copyrights for Compliance
#### Broken rules:
Copyright compliance needs to be resolved by revising copyright headers per requirements.

#### Suggestions to restore compliance:
Fix copyright headers.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #279

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling

**Review by kprusicka — APPROVED** [review]
The copyright headers now indeed include year 2023.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by kprusicka** [comment]
Dziekuje @BHoMBot

**Pull request merged**
