### PR TITLE
Fix error when pulling BarDeformationResults

### LINKED ISSUE #234: Pulling BarDeformation causes crash

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #234 

### Test files

[on Sharepoint](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/SAP2000_Toolkit/%23235-pull-barDeformation-crash?csf=1&web=1&e=qJpFn2)

expected (acceptable) results:
image

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check installer

**Comment by JosefTaylor** [comment]
@BHoMBot check installer

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by mchaf** [comment]
LGTM

**Review by mchaf — APPROVED** [review]
LGTM

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@BHoMBot check copyright-compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check dataset-compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
