### PR TITLE
Fix compliance issues

### LINKED ISSUE #74: Compliance issues
The following compliance issues have been found for this repository. Please see the checklist below.
#### Compliance issue for EngineClassMatchesFilePath
 - [ ] Incorrect Engine class name based on file path in SAP2000_Toolkit\SAP2000_Engine\AdapterIdName.cs at line 3, column 25 

#### Compliance issue for InputAttributeStartsLower
 - [ ] Input attribute should start with a lowercase letter in SAP2000_Toolkit\SAP2000_Adapter\SAP2000Adapter.cs at line 25, column 57 

#### Compliance issue for NameMatchesFileName
 - [ ] Class name must match file name in SAP2000_Toolkit\SAP2000_Engine\Convert\ToBHoM\Bar.cs at line 10, column 32 
 - [ ] Class name must match file name in SAP2000_Toolkit\SAP2000_Engine\Convert\ToBHoM\Constraint.cs at line 5, column 32 
 - [ ] Class name must match file name in SAP2000_Toolkit\SAP2000_Engine\Convert\ToBHoM\Loads.cs at line 11, column 32 
 - [ ] Class name must match file name in SAP2000_Toolkit\SAP2000_oM\Config\Config.cs at line 10, column 17 

#### Compliance issue for NameMatchesFileName
 - [ ] Method name must match file name in SAP2000_Toolkit\SAP2000_Engine\Modify\RigidLink.cs at line 15, column 38 
 - [ ] Method name must match file name in SAP2000_Toolkit\SAP2000_Engine\Modify\RigidLink.cs at line 39, column 38 

#### Compliance issue for ModifyReturnsSameType
 - [ ] Modify methods must return the same type as their first parameter in SAP2000_Toolkit\SAP2000_Engine\Modify\RigidLink.cs at line 15, column 22 

#### Compliance issue for IsValidConvertMethodName
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in SAP2000_Toolkit\SAP2000_Engine\Convert\ToBHoM\Bar.cs at line 16, column 29 
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in SAP2000_Toolkit\SAP2000_Engine\Convert\ToBHoM\Constraint.cs at line 11, column 37 
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in SAP2000_Toolkit\SAP2000_Engine\Convert\ToBHoM\Constraint.cs at line 33, column 33 
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in SAP2000_Toolkit\SAP2000_Engine\Convert\ToBHoM\Loads.cs at line 17, column 33 
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in SAP2000_Toolkit\SAP2000_Engine\Convert\ToBHoM\Loads.cs at line 72, column 31 
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in SAP2000_Toolkit\SAP2000_Engine\Convert\ToSAP2000\Bar.cs at line 16, column 29 
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in SAP2000_Toolkit\SAP2000_Engine\Convert\ToSAP2000\Constraint.cs at line 12, column 27 
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in SAP2000_Toolkit\SAP2000_Engine\Convert\ToSAP2000\Constraint.cs at line 35, column 27 
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in SAP2000_Toolkit\SAP2000_Engine\Convert\ToSAP2000\Material.cs at line 18, column 31 

#### Compliance issue for IsStaticClass
 - [ ] Invalid Engine class: Engine classes must be static in SAP2000_Toolkit\SAP2000_Engine\AdapterIdName.cs at line 3, column 4

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #74 

Convert methods moved to adapter namespace, filenames and input attribs updated per compliance.

### CODE REVIEW

**Comment by enarhi** [comment]
@FraserGreenroyd I anticipate one remaining compliance issue that may or not need changing. The toolkit includes a SplitRigidLink Modify method that returns a List<RigidLink> from a single RigidLink input. What is the suggested way to handle this per compliance / is this an acceptable case to make an exception?

**Comment by FraserGreenroyd** [comment]
> @FraserGreenroyd I anticipate one remaining compliance issue that may or not need changing. The toolkit includes a SplitRigidLink Modify method that returns a List from a single RigidLink input. What is the suggested way to handle this per compliance / is this an acceptable case to make an exception?

Hmm I would argue that that might be a `Compute` method, because it is doing more than just changing the given object. @awakeman , what are your thoughts?

**Comment by awakeman** [comment]
I'd agree, that or a `Query` method even, it's not a Modify because it's not conceptually modifying the object its passed, but performing an operation over it and returning something else (namely a collection of objects of the same type).

**Comment by enarhi** [comment]
Moved the RigidLink methods to query. Thanks for the quick input!

**Comment by enarhi** [comment]
azp run SAP2000_Toolkit.CheckCompliance

**Pull request merged**
