### PR TITLE
Added support for v23

### LINKED ISSUE #226: Support for SAP2000 V20,V22,V23
#### Description:

Hi, 

Working with BHoM recently and noticed that the SAP2000 function only support v21?
To the best of my knowledge the DLL files are similar for v20,v22 and v23 and use the same OAPI functions.

I was previously using VBA code to create function in grasshopper with the relevant DLL files.  I find BHoM intutive and would like to contribute to its development.

Thanks
David

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #226

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check core

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check null-handling

**Review by maryannewachter — APPROVED** [review]
Works with v21 per test cases outlined in #227

**Comment by JosefTaylor** [comment]
@BHoMBot check installer

**Comment by JosefTaylor** [comment]
@BHoMBot check versioning

**Comment by JosefTaylor** [comment]
@BHoMBot check versioning

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Comment by JosefTaylor** [comment]
@BHoMBot check versioning

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@BHoMBot nonsensical request

**Comment by FraserGreenroyd** [comment]
> @BHoMBot nonsensical request

👀

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Comment by JosefTaylor** [comment]
> 👀
I was really just asking BHoMBot to show me his wiki page. Could you put a link to that on BHoMBot's homepage, where it currently just says "It lives!"

**Pull request merged**
