### PR TITLE
Better Null checks

### LINKED ISSUE #154: SAP2000_Toolkit: Better null checks
#### Description:
Make sure all null cases are covered. Provide Note if element was created with the null property, Warnings if an element was created with some substitute property, and Error if element was not created.

Please add specific missing null check cases under this element if found.

#### Steps to reproduce:
Create SectionProperty  with null material
Create Surface Property with null material

#### Test file(s):

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/SAP2000_Toolkit/154%20-%20Issue%20-%20Null%20Checks/154%20Null%20Properties.gh?csf=1&web=1&e=CYb8ng

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #154 

### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Adapter/Structural_Adapter%20unit%20tests/Null%20objects%20check/Null%20objects%20test%20data.gh?csf=1&web=1&e=gUwALL

### CODE REVIEW

**Comment by JosefTaylor** [comment]
Panel from wrong discipline crashes adapter

**Comment by JosefTaylor** [comment]
Bar with offset whose x, y, and z, are null crashes adapter

**Comment by maryannewachter** [comment]
Notes for further improvements:

## Panels
- [ ] Default panel push does not trigger "Panel could not be created because geometry could not be determined"
- [ ] Single line edge panel  does not warn about invalid geometry
- [ ] General warning that openings cannot be pushed in SAP
- [ ] Complex non planar panel is not pushed and but returns success
- [ ] Null material on ribbed panel does not push panel but null material on waffle pushes a panel.

**Review by maryannewachter — DISMISSED** [review]
Tested against linked file and nonpassing checks noted for another PR. Other checks in linked file are passing without error.

**Comment by IsakNaslundBh** [comment]
I rebased this branch and force pushed it up again to fix conflict

## Please check that all changes have been correctly applied, and please delete the branch locally and re-pull it to your machine. Without doing this we might end up with duplicate commits that are hard/impossible to resolve

**Review by maryannewachter — APPROVED** [review]
Last commit has fixed all crashes for test files, additional null checks not implemented yet noted above, but ok to merge PR as is for other null checks.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Pull request merged**
