### PR TITLE
Added override to Delete method in toolkit.

### LINKED ISSUE #274: SAP2000 should be able to be deleted by object id
#### Description:

The Adapter.Remove function can only delete objects in SAP2000 by tag (ie. group name). The suggested feature will allow deletion of elements by object id as well through a FilterRequest.

### PR DESCRIPTION
**Pull request by andrbak**
… of elements by id.

   
### Issues addressed by this PR

Closes #274 

Added override to Delete method in toolkit. Thereby allowing deletion of elements by id.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
sorry, @andrbak , had missed this as I do not personally have access to SAP2000. For the same reason, I am unable to test this.

@mchaf @enarhi would you be able to assist?

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Review by enarhi — APPROVED** [review]
Testing using this [Test File](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/SAP2000_Toolkit/%23275-AddedDeleteMethod?csf=1&web=1&e=8YhnAL), delete worked as expected, removing elements with matching type and objectId from the model in SAP2000.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
