### PR TITLE
Revert "Fixing Load read/create bugs"

### PR DESCRIPTION
**Pull request by enarhi**
Reverts BHoM/SAP2000_Toolkit#219 due to a feature added. We need a new pr for this that does not include #217 as it is a feature.

### CODE REVIEW

**Comment by enarhi** [comment]
@JosefTaylor please run the checks and confirm the revert is acceptable. We will need a new pr that only addresses the other two issues which are bugs without adding features.

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check core

**Comment by JosefTaylor** [comment]
@BHoMBot check installer

**Comment by JosefTaylor** [comment]
@BHoMBot check versioning

**Review by JosefTaylor — APPROVED** [review]
worked before the commit, should work with the reversion!

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Comment by JosefTaylor** [comment]
@BHoMBot check ready to merge

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
