### PR TITLE
Correcting call to AdapterId

### LINKED ISSUE #208: Fix AdapterId method call again
#### Broken rules:

The AdapterId is calling the wrong method in Bar Update. THis was fixed previously, but new code has been added that calls the old method signature again, hence not compiling to https://github.com/BHoM/BHoM_Adapter/pull/287

#### Suggestions to restore compliance:

Fix the method call

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

   Aligns with https://github.com/BHoM/BHoM_Adapter/pull/287 again after some more code has been added. THis is also compiling to master though, so not fully dependant.

### Issues addressed by this PR

Closes #208

Could not use the same branch name as for the adapter as a PR had already been opened and merged fixing the issue before. Since then, new code has been added, where the issue has been re-introduced. This should compile to master though, hence this can be and needs to be merged before the Adapter PR.

### Test files

I do not have SAP2000 on my machine, but code functionality change from this PR should be non

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check all

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
I have done a code review of this in conjunction with the previous PRs and the open PRs on the Adapter which have brought about this change. The code change presented here appears robust and in line with the requirements of the changes to the adapter.

I am approving to unblock the merging of the Adapter PRs prior to the feature freeze so that this upgraded functionality is available in the 4.1 beta being produced in a couple of weeks. I have not been able to functionality test the changes, but have discussed with @IsakNaslundBh and agree that previous tests conducted on this work related to this toolkit should be sufficient for this to merge today. Nevertheless, CI/CD are taking responsibility for the merging of this particular PR. It is highly recommended (and indeed requested in no uncertain terms) that other members of this toolkits development team (@JosefTaylor @maryannewachter @jeanlucjackson , etc.) run tests that incorporate the changes made by this PR during the next sprint (which is focused on testing in advance of the 4.1 beta release).

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core

**Comment by IsakNaslundBh** [comment]
@BHoMBot  check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
