### PR TITLE
Fix beta-code-compliance failures

### LINKED ISSUE #301: Fix beta-code-compliance failures
#### Broken rules:

https://github.com/BHoM/SAP2000_Toolkit/pull/300/checks?check_run_id=22829655618

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #301 

### Changelog

- Fixed code-compliance failure with `AdapterIdName`

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check code-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check required
@BHoMBot check compliance

**Review by FraserGreenroyd — DISMISSED** [review]
Looks good to me - how did this get missed before? 😄

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 22949450241

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
All good following project compliance fixes.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
