### PR TITLE
Aligning to new AdapterIdFragment

### LINKED ISSUE #156: Remove use of CustomData in the code
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Create\Bar.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Create\LinkConstraint.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Create\Loads.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Create\Material.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Create\Node.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Create\Panel.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Create\RigidLink.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Create\Section.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Create\SurfaceProperty.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Read\Bar.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Read\LinkConstraint.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Read\Loads.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Read\Material.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Read\Node.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Read\Panel.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Read\RigidLink.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Read\Section.cs

 - [ ] SAP2000_Toolkit\SAP2000_Adapter\CRUD\Read\SurfaceProperty.cs

</p>
</details>

### PR DESCRIPTION
**Pull request by maryannewachter**
### NOTE: Depends on 
[BHoM/BHoM_Adapter#263](https://github.com/BHoM/BHoM_Adapter/pull/263)

   
### Issues addressed by this PR

Closes #156 

### Additional comments
Must be merged together with BHoM/BHoM_Adapter#263 and all others.

Partially tested by @JosefTaylor. Panels failing on push and issues with material fragments. 

Testing against [new script](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/Installers/Scripts/BuroHappold_BHoM_v.4.0/0023_Create%20-%20Read%20-%20Update%20-%20Structure%20Elements/BuroHappold_BHoM_v3.3.beta_Create%20-%20read%20-%20update%20elements%20-%20building.gh?csf=1&web=1&e=UXgQbA) only partially successful

### CODE REVIEW

**Comment by JosefTaylor** [comment]
fixed issues with null checks on bars and panels, since GetAdapterId crashes when called on a null, so some nullchecks which had been previously working (bar with null section, panel with null property) now caused crash.

**Review by JosefTaylor — DISMISSED** [review]
Looks good to me, although I was also the last person to touch the code...

**Comment by IsakNaslundBh** [comment]
There were some merge conflicts from the merging of branches into each other that made it impossible to rebase this branch:
image

I had to rebase and force push it to get rid of the conflicts.

**Review by IsakNaslundBh — APPROVED** [review]
Re-approving based on Josefs earlier approval

**Review by JosefTaylor — APPROVED** [review]
Works with the changes to Adapter

**Review by IsakNaslundBh — APPROVED** [review]
Approving based on checking together with @alelom and @JosefTaylor

**Pull request merged**
