### PR TITLE
Fixing BarRelease read and push

### LINKED ISSUE #248: Issue with partial fixity in frames
Hi! I have a problem when I try to model partial fixities at the end nodes of the frames. The set up is the following:

Captura

This only happens when I try to attach the partial stiffness to the end-points of the frames, which returns a null when I push the objects, whereas if I try to model springs in nodes this does not happen.

Can someone help me out with this?

Thanks in advance.

IMG

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #248

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/SAP2000_Toolkit/%23249-frame-partial-fixity?csf=1&web=1&e=kQsAy8

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@IsakNaslundBh I made all the same changes as in ETABS, check it out

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Review by mchaf — APPROVED** [review]
Ran test script and got expected results, LGTM

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 4777674079

**Pull request merged**
