### PR TITLE
fixed projected loading for distributed loading on bars

### LINKED ISSUE #180: BarUniformlyDistributedLoad only produces loads in Global Coordinates
#### Description:

BarUniformlyDistributedLoad produces a distributed load in the Global Coordinate system, even when a projected load flag is applied.

#### Steps to reproduce:
Push projected uniformly distributed load into SAP2000.

#### Expected behaviour: 
Values from same bar test file should match for global vs. projected loads applied.

#### Test file(s):
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/Installers/Scripts/BuroHappold_BHoM_v3.3/0027_Create%20Read%20Loads/BuroHappold_BHoM_v3.3.beta_Create%20read%20loads.gh?csf=1&web=1&e=fO9wtD

### PR DESCRIPTION
**Pull request by maryannewachter**
### Issues addressed by this PR

Fixes #180 

### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/Installers/Scripts/BuroHappold_BHoM_v3.3/0027_Create%20Read%20Loads/BuroHappold_BHoM_v3.3.beta_Create%20read%20loads.gh?csf=1&web=1&e=fO9wtD

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
This PR will need a label before merging just as a reminder :smile:

**Review by JosefTaylor — APPROVED** [review]
LGTM!

**Comment by JosefTaylor** [comment]
@BHoMBot check installer

**Pull request merged**
