### PR TITLE
Fix FilterIds() and Create(LoadCombination)

### LINKED ISSUE #210: SAP2000_Adapter: FilterIds crashes if no objects (of the relevant type) are present in SAP model
#### Description:

Attempting to read an object type where none exist in the SAP model fails because the list of SAP IDs for the existing objects are passed to FilterIds to compare to the requested IDs, but FilterIds does not check if the list is empty.

### LINKED ISSUE #211: SAP2000_Toolkit: Load Combination push fails if LoadCombo doesn't contain AdapterId
#### Description:

if you create a load Combo which uses loadCase which has not been pushed to SAP, or is one which has been pushed in previous actions, but doesn't contain the AdapterId, the Load Combo will fail.

### LINKED ISSUE #213: ActionConfig won't cast to SAP2000PushConfig, causes crash
#### Description:

if Update is called (which uses SAP2000PushConfig) and no ActionConfig, or a generic ActionConfig is supplied, the IUpdate() method crashes on trying to cast actionConfig to a SAP2000PushConfig.

I'm not sure if a change upstream caused this behavior, but it is new since the work on Update was done.

### LINKED ISSUE #214: ReplaceLoads in SAP2000PushConfig is ignored
#### Description:

ActionConfigs are not handled in ICreate, so the ReplaceLoads configuration is ignored, and all loads are replaced by default.

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #210
Closes #211
Closes #213 
Closes #214

- Fixed `FilterIds(ids, sapIds)` so that ids and `sapIds` can both be null and still return a value (an empty list, if `sapIds` is null)
- Fixed `Create(LoadCombination, etc.)` so that if the inner `LoadCase` can be referenced either by name or AdapterId (since AdapterId is always the name, anyway) which allows pushing `LoadCombinations` which reference 'LoadCases' which are in the model, but don't have AdapterIds - this allows pushing case and combo at the same time, without using a previously pulled/pushed case which has an adapterId. It is still not possible to push only a LoadCombination and get the constituent cases pushed as well, in spite of the dependancy type being set up.
- Override `SetupPushConfig` to cast the provided `ActionConfig` to a `SAP2000PushConfig`, and creating a new instance if that fails. This ignores any settings in `ActionConfig` if they are used.
- Set SAPPushConfig from ICreate(), so that loads respect the user's selection of 'ReplaceLoads' in the config.

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/SAP2000_Toolkit/%23212%20bug%20fixes%20-%20filterId%20Create%20load%20actionConfig?csf=1&web=1&e=6FWan5

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check core

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check core

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check installer

**Comment by JosefTaylor** [comment]
@BHoMBot check versioning

**Review by enarhi — APPROVED** [review]
LGTM. Noting here that the Load Case / Load Combination push still only works if the case is pushed before the combo, with a warning that the combo was created without the case if the combination is pushed first. This can be resolved as a separate issue.

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
