### PR TITLE
BarResult divisions fixed and modest speed improvements

### LINKED ISSUE #171: BarResultRequest divisions not working
#### Description:
BarResultRequest currently returns the sap division amount  no matter what is input into the divisions parameter. It is also prohibitively slow for large result sets, partly due to id handling that we may be able to optimize.

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #171 

SAP does not allow specifying how many output stations to pull, so the Pull will now return a note to that effect, and the results output will show the number of divisions returned.

Also, a few bits of code were streamlined, hopefully resulting in modest performance enhancements. 

### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/SAP2000_Toolkit/%23171-BarResultRequest%20divisions%20not%20working/Pull%20Structural%20Analysis%20Results.gh?csf=1&web=1&e=4H30H3

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot  check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check core

**Comment by JosefTaylor** [comment]
@BHoMBot check installer

**Comment by JosefTaylor** [comment]
@BHoMBot check ready merge

**Comment by JosefTaylor** [comment]
@BHoMBot check ready to merge

**Comment by FraserGreenroyd** [comment]
@JosefTaylor the command is in full for this check is @BHoMBot check ready-to-merge (which will now trigger but will fail cause this isn't ready to merge owing to a lack of approving review :smile: )

**Comment by JosefTaylor** [comment]
@FraserGreenroyd I was going to ask about that this morning- can we get more consistency in these commands, or is there a document somewhere? Like can we issue two commands in one comment?

**Comment by jcparker64** [comment]
Speed improved!

**Review by maryannewachter — APPROVED** [review]
LGTM. I don't have a massive model to test on (yet), but divisions works with custom divisions for extracting internal forces at each station.

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Comment by JosefTaylor** [comment]
@FraserGreenroyd @BHoMBot is ignoring me!

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
