### PR TITLE
Panel to return empty list of openings instead of null

### LINKED ISSUE #232: SAP2000_Toolkit: Pulling panels raises Geometry Extension error due to null Openings
#### Description:

Panel openings have no equivalent in SAP2000, so the read method returns a null, but recent changes to the preview methods can't accept a null here and throw an error.

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #232 

### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/SAP2000_Toolkit/%23233%20empty%20panel%20vs%20null/PR233%20pull%20panels.gh?csf=1&web=1&e=B9F0oe

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Review by mchaf — APPROVED** [review]
LGTM

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
