### PR TITLE
Implemented Bar Utilisation Read Functionality

### LINKED ISSUE #183: Add Additional BarResults Pull Functionality
#### Description:
Add ability to get more BarResults beyond BarForces.

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #183 

Added ability to pull utilisation results from SAP. This includes the addition of a new AISCSteelUtilisationClass and corresponding request and enum as per discussion with @JosefTaylor and @IsakNaslundBh . Long term, these additions should be migrated to BHoM as they are not SAP-specific.

### Test files
[PullSAPUtilisation.zip](https://github.com/BHoM/SAP2000_Toolkit/files/5897225/PullSAPUtilisation.zip)

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check installer

**Comment by maryannewachter** [comment]
LGTM. Note that currently all AISC 360_XX work for pulling results but reference in output object provides correct year (i.e. you can input AISC  360_16 and requesting AISC_360_10 will work, but produce AISC_360_16 in the output "DesignCodeReference")

**Review by maryannewachter — APPROVED** [review]
LGTM. See comment above.

**Pull request merged**
