### PR TITLE
Added null handling to eliminate failed push bug on empty tag

### LINKED ISSUE #272: Basic Panel push is failing due to tag string check without null handling
#### Description:
Pushing panels with no tags results in a cryptic error and a failed push.

#### Steps to reproduce:
Push a basic panel without tags, using default push settings.

#### Expected behaviour:
Proper panel creation in SAP2000.

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #272 

Adds null handling to tag string check to avoid error when processing tags if one of them is null.

### Test files
[Test File](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/SAP2000_Toolkit/%23272-Push-panels?csf=1&web=1&e=7J3Xjq)

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Review by IsakNaslundBh — APPROVED** [review]
I do not have access to SAP2000, so unable to test, but given the scope of the changes I am ready to approve on just code review.

Simple null check added, cannot see how this could be causing any issues elsewhere.

Approved

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
