### PR TITLE
Fixing read/create load bugs

### LINKED ISSUE #216: Creating Unsupported Load types causes crash

### LINKED ISSUE #217: Creating projected loads is implemented, but reading them is not.

### LINKED ISSUE #218: Create Bar Point load assumes that DistanceFromA is relative to bar length, but it is absolute.

### PR DESCRIPTION
**Pull request by JosefTaylor**
fixed issues with replace loads, absolute vs. relative location of BarPointLoad, and not implemented errors.

### Issues addressed by this PR

Closes #216 
Closes #218

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check core

**Comment by JosefTaylor** [comment]
@BHoMBot check versioning

**Review by enarhi — APPROVED** [review]
LGTM

**Pull request merged**
