### PR TITLE
Updating supported versions

### LINKED ISSUE #255: Readme out of date
#### What is missing/incorrect?

Versions of SAP supported
Object Relations Table

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #255 

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/SAP2000_Toolkit/%23256-documentation-update?csf=1&web=1&e=HrxMnn

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check installer

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance
@BHoMBot check installer

**Comment by JosefTaylor** [comment]
Hey @murali-manoj , I know you won't be able to use this because you haven't got SAPv21, but could you check that you get a reasonable error message which tells you that SAPv20 is not supported?

@mchaf can you make sure this builds and runs? Basic functionality only.

**Review by IsakNaslundBh — DISMISSED** [review]
Only changes are to Read me and Descriptions added. Approving on this basis and code review.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Review by IsakNaslundBh — APPROVED** [review]
Reapproving on same basis as above.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
