### PR TITLE
Fix Create(GeometricalLineLoad)

### LINKED ISSUE #267: Geometrical Line Loads do not push
#### Description:

GeometricalLineLoads successfully push a null bar, but then fail to load it, because it uses distance from each end instead of relative position, i.e. start = end = 0 vs start = 0 end = 1.

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #267

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/Installers/Scripts/Burohappold_BHoM_v5.3/Structures%20-%20Create%20read%20loads?csf=1&web=1&e=TLDYka

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Review by mchaf — APPROVED** [review]
I opened the test script that Joe created. I pushed the geometric line load at the bottom of the script, and the line load properly pushed in SAP. There is an error when you pull the line load back into GH, but there is an error message that clearly explains the problem. LGTM

**Comment by mchaf** [comment]
@BHoMBot Check ready-to-merge

**Pull request merged**
