### PR TITLE
Add support for TaperedProfile and a versioning fix

### LINKED ISSUE #105: SAP2000_Toolkit: Support tapered profiles

### LINKED ISSUE #206: Versioning failure for SAP2000ActionConfig
Versioning for `SAP2000ActionConfig` is broken by the rename to `SAP2000PushConfig` in [this PR](https://github.com/BHoM/SAP2000_Toolkit/pull/204). Needs resolving critically before the beta and beta testing.

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #105
Closes #206 

Added support for reading and creating tapered profiles i.e. TaperProfile

### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/SAP2000_Toolkit/%23105-Tapered-Profiles/Create%20and%20Read%20Tapered%20Profile.gh?csf=1&web=1&e=jU0kJ3

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check versioning

**Comment by JosefTaylor** [comment]
@BHoMBot check core

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check core

**Comment by JosefTaylor** [comment]
@BHoMBot check versioning

**Review by jcparker64 — APPROVED** [review]
Looks good!

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check core

**Comment by JosefTaylor** [comment]
@BHoMBot check installer

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Review by enarhi — APPROVED** [review]
LGTM

**Review by maryannewachter — APPROVED** [review]
Works as expected. Recommend that TaperedSection raise an exception if a higher interpolation order is input than possible, rather than defaulting to what's allowed.

**Pull request merged**
